### ISSUE TITLE
Pub Med IDs

### ISSUE THREAD

**Issue by kkubiak89** [kepski/BdK6.5.3._P3_SOSE2021_Vera_Kepski#1]
Die Informationen sind in weiteren Dictionaries versteckt. Wenn du 
data_id1["result"]["uids"][0] eingibst, wird dir die ID angegeben. Diese setzt du dann ein, bei dir wäre das 27708327
Wenn du dann data_id1["result"]["27708327"]["title"] eingibst, sollte er dir den Titel herausgeben. Das funktioniert dann auch mit "pubdate"

**Comment by kepski** [comment]
Vielen Dank! Damit hat es super geklappt :-)
